<a href="https://colab.research.google.com/github/shyamjith94/PyTorch/blob/main/PytorchAutoGradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
%%capture
!pip install torch torchvision

In [10]:
import torch, torchvision

In [11]:
# requires_grad - computational tracking
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [12]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x+1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [13]:
y.backward()
x.grad

tensor(93.)

In [15]:
x = torch.tensor([[1., 2., 3.], [3.,2.,1]], requires_grad=True)
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [16]:
y = 3*x+2

In [17]:
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [18]:
z = 2*y**2
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [19]:
out = z.mean()

In [20]:
out.backward()
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])